{
  parserClass="com.razomy.notation.idea.plugin.RnParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Rn"
  psiImplClassSuffix="Impl"
  psiPackage="com.razomy.notation.idea.plugin"
  psiImplPackage="com.razomy.notation.idea.plugin.impl"

  elementTypeHolderClass="com.razomy.notation.idea.plugin.RnTypes"
  elementTypeClass="com.razomy.notation.idea.plugin.RnElementType"
  tokenTypeClass="com.razomy.notation.idea.plugin.RnTokenType"
  psiImplUtilClass="com.razomy.notation.idea.plugin.RnPsiImplUtil"

}

RnFile ::= item_*

private item_ ::=   COMMENT
                    | (PROPERTY EMPTY_LINE)
                    | ERROR

PROPERTY ::= (KEY END)
             | (KEY SEPARATOR VALUE END)
             | (KEY CHILD_DEEP PROPERTY* END)
             | (KEY SEPARATOR VALUE CHILD_DEEP PROPERTY* END)
{
  methods=[getKey getValue]
}